# Generated by Django 4.2.30 on 2026-09-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_department_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.TextField(blank=True, default=""),
        ),
    ]
