# Generated by Django 4.2.30 on 2026-09-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_alter_faculty_options_alter_nodues_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
